name: Build Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, gh-pages ]
  workflow_dispatch:

jobs:
  build-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Block gh-pages merges
      if: github.base_ref == 'gh-pages'
      run: |
        echo "##################################################"
        echo "不允许直接合并到 gh-pages 分支!!!"
        exit 1

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Install dependencies
      run: |
        npm install 
        npm install -g hexo
        npm ci
        sudo apt-get install tidy -y
        
    - name: Install theme dependencies  
      run: |
        cd themes/default
        npm install
        cd ../..

    - name: Clean 
      run: npx hexo clean

    - name: Build check
      run: |
        # 使用 --debug 模式生成,这样会输出更详细的错误信息
        npx hexo generate --debug

    - name: Check HTML files
      run: |
        # 检查生成的 HTML 文件是否有问题
        find public -name "*.html" -exec tidy -e {} \;