name: Branch Protection & Build Validation

on:
  pull_request:
    branches: [ main, gh-pages ]

jobs:
  build-check:
    if: github.base_ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Build Check
        id: build
        run: |
          # 运行构建命令
          if ! npm run build; then
            echo "构建失败"
            exit 1
          fi
          
      - name: Validate Output
        run: |
          # 检查生成的文件是否有效
          if find ./dist -type f -name "*.html" -exec tidy -eq {} \; 2>/dev/null; then
            echo "HTML 验证通过"
          else
            echo "发现无效的 HTML 文件"
            exit 1
          fi

  protect-gh-pages:
    if: github.base_ref == 'gh-pages'
    runs-on: ubuntu-latest
    steps:
      - name: Block gh-pages merges
        run: |
          echo "禁止直接合并到 gh-pages 分支"
          exit 1